import { Montserrat } from "next/font/google";
import "./styles/globals.scss";
import { ShoppingBasketContextProvider } from "./components/shoppingBasket";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Daintree",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <ShoppingBasketContextProvider>
          {children}
        </ShoppingBasketContextProvider>
      </body>
    </html>
  );
}
